### ISSUE TITLE
SH3D doors; Furniture XY rotation

### ISSUE THREAD

**Issue by MarinPoete** [rostskadat/FreeCAD-SH3D#1]
Hi,
The import works quite well however I noticed that
- some SH3D doors are not imported (for example Entrance door by Kator Legaz or by Seber Liber)
- X or Y rotation of furnitures  is not respected
Best Regards

**Comment by rostskadat** [comment]
Hello @MarinPoete 

Do you happen to have an example of such behavior? Ideally an SH3D file showing the problem...

Thanks

**Comment by MarinPoete** [comment]
Hi Julien
In attachment a ’Test simple’ SH3D  and its import result  into Freecad 
As you will notice 2 doors are missing and the upper red timber is not rotated as in SH3D 
My versions 
SH3D : 7.5.1 Mac 
FCad : 0.21.2 - 33771
Thanks

**Comment by rostskadat** [comment]
Bonjour @MarinPoete ,

Would you mind attaching the file in GitHub directly? I think that if you attach it to the email instead, it will not appear in the GitHub bug report.

Thanks.

**Comment by MarinPoete** [comment]
As I can't put them directly , 
[Archive.zip](https://github.com/user-attachments/files/17071908/Archive.zip)
I've  compressed the 2 files in an archive

**Comment by rostskadat** [comment]
Thanks @MarinPoete , I'll have a look at the file and how it is imported and come back to you

**Comment by rostskadat** [comment]
Hello @MarinPoete  

About the door not importing: it is due to the fact that the import tries to use the `Arch.makeWindowPreset()` to create the window/door. The way it works is to determine a correspondence between the SH3D `catalogId` with a specific `Arch.WindowPresets`. When such  correspondence can not be determine, it refused to create the window/door. One of the consequences of this approach is the fact that all the frills (coming from the mesh itself) are lost during import.
It seemed more important to preserve the IFC characteristics of the window/door than the other element (such as door handle, etc.).

The behavior has been changed to just create a `Simple Door`. 

However, I wonder if that is the correct behavior. A better approach would be to let the user select the best correspondence and somehow remember it for the next time. However this is a little bit beyond what I know how to do with FreeCAD.

I'll investigate the coordinate problem now.

**Comment by rostskadat** [comment]
Hello @MarinPoete 

The pitch and roll indicated in the SH3D file was ignored. It should be fixed now. Please confirm that it is fixed in your version as well. Fell free to re-open the issue if that is not the case

Thanks for your help

**Comment by MarinPoete** [comment]
Julien,
Yes it is fixed (-: and by the way I've seen that you did also something for doors and invisible boxes. Thanks
For staircases (and SVG)  may be you should have a look. I've added them in my simple test in att.
Best Regards
[Archive.zip](https://github.com/user-attachments/files/17127678/Archive.zip)
